### ISSUE TITLE
Penilaian Progress-2 ShinyDBApps

### ISSUE THREAD

**Issue by alfanugraha** [MDS-kelompok8/Tugas-Kelompok-8#2]
## **NILAI: 77**  

Catatan untuk penyempurnaan

> 1. Sebaiknya dihilangkan jika tidak diperlukan atau tidak berfungsi, begitu juga pada halaman lain banyak terdapat selectInput yang tidak berjalan

![k8unused](https://user-images.githubusercontent.com/5440894/224965850-8bb0da0c-9981-43e4-b2ac-6d43d1a751c9.png)

> 2. Bagian ini akan lebih informatif jika dilakukan query dengan menampilkan daftar film beserta genre, daftar pemain, sutradara, dan rating

![k8rating](https://user-images.githubusercontent.com/5440894/224964575-6614deb3-7a6e-4cf6-8e56-bd2ae2d9a3ab.png)

**Comment by MDS-kelompok8** [comment]
Terima kasih sarannya, Mas Alfa.. 
Untuk bagian 'selectInput' nantinya akan dibuat filter berdasarkan judul, genre, actor, dan sebagainya. Tapi memang belum dikembangkan lagi querynya.
Untuk bagian lainnya kami memang baru menampilkan tabel mas, belum dibuat select query, nanti kami revisi lagi yaa mas. Terima kasih.
